# lib/app.py
print("Hello world!")
print(2/3)
print(2//3)
print(2%3)
print("Hello sun!")
print("Hello sky!")
print("Hello world!", end=" ")
print("Hello sun!", end="!! ")
print("Hello sky!", end="!!!\n")
print("Hello Python shell")